fix(l2): disable gpu in `make lint` target (#4048)
**Motivation**

`make lint` was failing with:

```text
warning: risc0-sys@1.4.0: Compiler family detection failed due to error: ToolNotFound: failed to find tool "nvcc": No such file or directory (os error 2)
error: failed to run custom build command for `risc0-sys v1.4.0`

Caused by:
  process didn't exit successfully: `/Users/mega/execution/ethrex/target/release/build/risc0-sys-d088ac4aaf714579/build-script-build` (exit status: 1)
  --- stdout
...(a lot of lines)

  --- stderr


  error occurred in cc-rs: failed to find tool "nvcc": No such file or directory (os error 2)
```

**Description**

This PR removes the `--all-features` flag and replaces it with `-F` and
a list of all features minus the "gpu" one that caused the problem
(`--all-features` is kept for L2 lint workflow). I got the list of
features with `cargo add -n ethrex`.