fix(l1): remove trailing commas in genesis-l1-dev (#2435)
**Motivation**

In #2418 the genesis-l1-dev.json test file is edited, adding trailing
commas. This causes the L2 integration test to fail with:

```
thread 'main' panicked at cmd/ethrex/utils.rs:59:40:
Failed to decode genesis file: Error("trailing comma", line: 36, column: 5)
```

**Description**

Removes both instances of trailing commas in genesis-l1-dev.json